name = "gentle-rain"
main = "src/worker.js"
compatibility_date = "2022-12-20"
account_id = "8232125ce8ea42c46f11e2ded2a8e422"

workers_dev = true
kv_namespaces = [
    { binding = "VIEWS", id = "c33224aa7d85416c8579bf5d8b95c2f7", preview_id = "c33224aa7d85416c8579bf5d8b95c2f7" }
]

[env.production]
workers_dev = false
zone_id = "3b45eda9555aecf6c720d5538c8393fa"
route = "crudman.cn/*"
kv_namespaces = [
    { binding = "VIEWS", id = "66a0161821d84473a12bb45904177b08" }
]